Remove extra includes field from library.properties
The second includes field overrides the first, causing Sketch > Include Library > Flash Library to add only the following line to the sketch:

#include <flash.cpp>

When the sketch is compiled this gives the error:

fatal error: flash.cpp: No such file or directory